# VPP hugepages and shared memory configuration
# Applied automatically by bng-stack-runtime package

# Number of 2MB hugepages
vm.nr_hugepages=1024

# max_map_count >= 2 * nr_hugepages
vm.max_map_count=3096

# All groups allowed to access hugepages
vm.hugetlb_shm_group=0

# Shared memory max (must be >= hugepages total size: 1024 * 2MB = 2GB)
kernel.shmmax=2147483648
